routes:
  - match: "/api/users"
    rewrite: "/api/users"
    target: "http://localhost:8080"

  - match: "/api/books"
    rewrite: "/api/books"
    target: "http://localhost:8080"

  - match: "/api/books/{id}"
    rewrite: "/api/books/{id}"
    target: "http://localhost:8080"