routes:
  - match: "/api/users"
    rewrite: "/api/users"
    target: "http://127.0.0.1:8080"

  - match: "/api/books"
    rewrite: "/api/books"
    target: "http://127.0.0.1:8080"

  - match: "/api/books/{id}"
    rewrite: "/api/books/{id}"
    target: "http://127.0.0.1:8080"

  - match: "/api/genres"
    rewrite: "/api/genres"
    target: "http://127.0.0.1:8080"

  - match: "/api/genres/{id}"
    rewrite: "/api/genres/{id}"
    target: "http://127.0.0.1:8080"

  - match: "/api/authors"
    rewrite: "/api/authors"
    target: "http://127.0.0.1:8080"

  - match: "/api/authors/{id}"
    rewrite: "/api/authors/{id}"
    target: "http://127.0.0.1:8080"